version: "3.9"

services:
  db:
    image: library/postgres:13
    restart: always
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pets
      POSTGRES_USER: django_pets
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASSWORD
    secrets:
      - DB_PASSWORD
  web:
    depends_on:
      - db
    image: python:3
    working_dir: /pets
    volumes:
    - ./pets/:/pets
    ports:
    - 800:8001
    command: bash -c "
      pip install -r requirements.txt
      && python manage.py migrate --settings=settings.docker
      && python manage.py runserver --settings=settings.docker 0.0.0.0:8001"
    environment:
      APP_DB_ENGINE: django.db.backends.postgresql
      DB_NAME: pets
      DB_USER: django_pets
      DB_HOST: db
      DB_PORT: 5432
      SECRETS_PATH: /run/secrets
    secrets:
      - AWS_SECRET_ACCESS_KEY
      - API_KEY
      - SECRET_KEY
      - DB_PASSWORD
secrets:
  AWS_SECRET_ACCESS_KEY:
    file: secrets/aws_secret_access_key.secret
  API_KEY:
    file: secrets/api_key.secret
  DB_PASSWORD:
    file: secrets/db_password.secret
  SECRET_KEY:
    file: secrets/secret_key.secret
